name: Build PSP Game

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup PSP toolchain
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake wget git python3
        wget https://github.com/pspdev/pspdev/releases/latest/download/pspdev-ubuntu-latest.tar.gz
        tar -xzf pspdev-ubuntu-latest.tar.gz -C $HOME
        echo "$HOME/pspdev/bin" >> $GITHUB_PATH

    - name: Build project
      run: |
        export PATH="$HOME/pspdev/bin:$PATH"
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PSP-Game
        path: |
          *.iso
          *.cso
          EBOOT.PBP
