name: Build PSP Game

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pspdev/pspdev:latest   # ใช้ docker image ที่มี toolchain แล้ว

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build project
      run: |
        export PATH="/usr/local/pspdev/bin:$PATH"
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PSP-Game
        path: |
          *.iso
          *.cso
          EBOOT.PBP
