name: Build PSP Game

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup PSP toolchain
      run: |
        sudo apt update
        sudo apt install -y build-essential git cmake python3 wget
        export PSPDEV=$HOME/pspdev
        export PATH=$PSPDEV/bin:$PATH
        git clone https://github.com/pspdev/psptoolchain.git
        cd psptoolchain
        ./toolchain.sh
        echo "PSPDEV=$PSPDEV" >> $GITHUB_ENV
        echo "PATH=$PSPDEV/bin:$PATH" >> $GITHUB_ENV

    - name: Build project
      run: |
        export PSPDEV=$HOME/pspdev
        export PATH=$PSPDEV/bin:$PATH
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PSP-Game
        path: |
          *.iso
          *.cso
          EBOOT.PBP
