name: Build PSP Game

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PSPDEV: ${{ github.workspace }}/pspdev
      PSPSDK: ${{ github.workspace }}/pspdev/psp/sdk

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup PSP toolchain
      run: |
        sudo apt update
        sudo apt install -y build-essential git cmake python3 wget
        git clone https://github.com/pspdev/psptoolchain.git
        cd psptoolchain
        ./toolchain.sh
        echo "$PSPDEV/bin" >> $GITHUB_PATH

    - name: Build project
      run: |
        export PATH="$PSPDEV/bin:$PATH"
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PSP-Game
        path: |
          *.iso
          *.cso
          EBOOT.PBP
