name: Build PSP Game

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build with pspdev Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace pspdev/pspdev make

    - name: Upload EBOOT.PBP
      uses: actions/upload-artifact@v3
      with:
        name: EBOOT
        path: EBOOT.PBP
