name: Build PSP Game

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PSP toolchain (Docker)
        uses: docker://dockcross/pspdev:latest

      - name: Build with make
        run: |
          make

      - name: Upload PSP EBOOT
        uses: actions/upload-artifact@v4
        with:
          name: EBOOT
          path: EBOOT.PBP
